### ISSUE TITLE
Is there a typescript defenition for this?

### ISSUE THREAD

**Issue by Yorkst** [terkelg/math-toolbox#7]

**Comment by Yorkst** [comment]
I generated one.

`export function almostIdentity(x: number, m: number, n: number): number;

export function average(...args: number[]): number;

export function clamp(min: number, max: number, v: number): number;

export function clamp01(v: number): number;

export function closestPowerOfTwo(value: number): number;

export function cubicPulse(c: number, w: number, x: number): number;

export function degToRad(degrees: number): number;

export function deltaAngle(a: number, b: number): number;

export function deltaAngleDeg(a: number, b: number): number;

export function deltaAngleRad(a: number, b: number): number;

export function deltaTime(oldTime: number, newTime?: number): number;

export function diagonal(w: number, h: number): number;

export function difference(a: number, b: number): number;

export function distance(x1: number, y1: number, x2: number, y2: number): number;

export function expStep(x: number, k: number, n: number): number;

export function fract(v: number): number;

export function fuzzyCeil(value: number, epsilon?: number): number;

export function fuzzyEqual(a: number, b: number, epsilon?: number): number;

export function fuzzyFloor(value: number, epsilon?: number): number;

export function fuzzyGreaterThan(a: number, b: number, epsilon?: number): number;

export function fuzzyLessThan(a: number, b: number, epsilon?: number): number;

export function gammaToLinearSpace(v: number): number;

export function gcd(a: number, b: number): number;

export function impulse(k: number, x: number): number;

export function inverseLerp(a: number, b: number, v: number): number;

export function inverseMix(a: number, b: number, v: number): number;

export function isEven(number: number): boolean;

export function isOdd(number: number): boolean;

export function isPowerOfTwo(value: number): boolean;

export function lerp(x: number, y: number, r: number): number;

export function lerpAngle(a: number, b: number, t: number): number;

export function lerpAngleDeg(a: number, b: number, t: number): number;

export function lerpAngleRad(a: number, b: number, t: number): number;

export function lerpUnclamped(x: number, y: number, a: number): number;

export function linearToGammaSpace(v: number): number;

export function map(value: number, start1: number, stop1: number, start2: number, stop2: number): number;

export function maxAdd(value: number, amount: number, max: number): number;

export function minSub(value: number, amount: number, min: number): number;

export function mix(x: number, y: number, r: number): number;

export function mixUnclamped(x: number, y: number, a: number): number;

export function mod(a: number, n: number): number;

export function nextPowerOfTwo(v: number): number;

export function normalize(min: number, max: number, x: number): number;

export function parabola(x: number, k: number): number;

export function percent(a: number, b: number, base?: number): number;

export function powerCurve(x: number, a: number, b: number): number;

export function radToDeg(radians: number): number;

export function randomFloat(minValue: number, maxValue: number, precision?: number): number;

export function randomInt(min: number, max: number): number;

export function randomSign(): number;

export function smoothMax(a: number, b: number, k: number): number;

export function smoothMin(a: number, b: number, k: number): number;

export function smoothStep(min: number, max: number, v: number): number;

export function step(edge: number, v: number): number;

export function toDegrees(radians: number): number;

export function toRadians(degrees: number): number;

export function within(a: number, b: number, tolerance: number): boolean;

export function wrap(value: number, min: number, max: number): number;

`

**Comment by terkelg** [comment]
Hi @Yorkst 
Thanks for the typescript defenition. I don't use it myself, but I'm open to add it to the repo.

**Comment by Yorkst** [comment]
I updated it. Can you add it to your rollup configuration somehow?

**Comment by terkelg** [comment]
I've never used TypeScript and I'm not sure how it's supposed to work.
Can you do a pull-request?
