### ISSUE TITLE
percent is unclear and its documentation is wrong

### ISSUE THREAD

**Issue by Yorkst** [terkelg/math-toolbox#8]
https://github.com/terkelg/math-toolbox/blob/master/src/percent.js
 * @param  {integer} number - The number to check.
It has no parameter {integer}
The error is here as well: https://terkelg.github.io/math-toolbox/#percent

https://github.com/terkelg/math-toolbox/blob/master/test/percent.test.js
it('Expect 125 of 100 to be 1', () => 
Isn't 125 125% of 100?
What does the function do?

**Comment by terkelg** [comment]
Thanks for flagging the issue. Appreciate that, I'll look at it.

The function returns a percentage in a more code friendly way.
I find percentage is entered in the range 0-1 most of the time.
This is a function to convert and clamp a percentage to that range.

Thanks

**Comment by terkelg** [comment]
A better name could be `percentToDecimal`. And then add a `percent` function too.

**Comment by Yorkst** [comment]
Probably percent01Clamped for current version? And percent01 separately? percentToDecimal doesn't address clamping and  percentToDecimalClamped is too long

**Comment by terkelg** [comment]
I think `percent01Clamped`is a bit too long, since it's a function I use often. Maybe `percent01` and `percent01Unclamped`. Maybe combine them into the same function and add clamping as a parameter.

**Comment by terkelg** [comment]
Fixed in v1.12.0 b8c7153
